server:
  port: 6061

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
custom:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: postgres


